@startuml
'https://plantuml.com/sequence-diagram

!$sessionToken = "[sessionToken]"
!$tile_http_resp = "[Tile HTTP response]"

Client -> DefaultGoogleMapsTileService: createSession(String language, String format)
DefaultGoogleMapsTileService -> WebClient: Make http request to google: POST /createSession with: language, format, apiKey
WebClient --> DefaultGoogleMapsTileService: $sessionToken
DefaultGoogleMapsTileService --> Client: $sessionToken

@enduml