@startuml
'https://plantuml.com/sequence-diagram

!$sessionToken = "[sessionToken]"
!$tile_http_resp = "[Tile HTTP response]"

Client -> DefaultGoogleMapsTileService: tileExists(tileCoordinates, $sessionKey)

DefaultGoogleMapsTileService -> WebClient: Make http request to google: GET /tiles with: tileCoordinates, $sessionToken
WebClient --> DefaultGoogleMapsTileService: $tile_http_resp

alt $tile_http_resp.status = 404 Not Found
    DefaultGoogleMapsTileService --> Client: False
else $tile_http_resp.status = 200 OK
    DefaultGoogleMapsTileService --> Client: True
else
    DefaultGoogleMapsTileService --> Client: error: WebClientResponseException
end

@enduml