@startuml

!$tileCoordinates = "[tileCoordinates]"
!$tileCoordinates1 = "[tileCoordinates1]"
!$tileCoordinates2 = "[tileCoordinates2]"
!$EMPTY = "[EMPTY]"

Client -> DefaultNoTileAreaService: cacheNoTileArea($tileCoordinates, format)

DefaultNoTileAreaService -> DefaultNoTileAreaService: findNoTileAreaTileCoordinates(<tile coordinates>, format)
activate DefaultNoTileAreaService
    DefaultNoTileAreaService -> SessionContextProvider: sessionContext(defaultLanguage, format)
    SessionContextProvider --> DefaultNoTileAreaService: sessionContext
    DefaultNoTileAreaService -> GoogleMapsTileService: tileExists($tileCoordinates, sessionKey)
    GoogleMapsTileService --> DefaultNoTileAreaService: tileExist: boolean
    DefaultNoTileAreaService -> DefaultNoTileAreaService: find geographical coordinates for $tileCoordinates
    DefaultNoTileAreaService --> DefaultNoTileAreaService: add lower zoom to no tile area. Returns: $tileCoordinates1, $tileCoordinates2
deactivate DefaultNoTileAreaService

DefaultNoTileAreaService -> NoTileAreaRepository: create($tileCoordinates1, $tileCoordinates2, ttl) \n- save coordinates in cache
NoTileAreaRepository --> DefaultNoTileAreaService
DefaultNoTileAreaService --> Client

@enduml