@startuml

Client -> GoogleSatelliteImageService: getMaxSupportedZoom
GoogleSatelliteImageService -> NoTileAreaService: getMaxSupportedZoom - get max supported zoom from to-tile cache
NoTileAreaService --> GoogleSatelliteImageService: response = max_supp_zoom or null
GoogleSatelliteImageService -> MaxZoomService: getMaxSupportedZoom
MaxZoomService --> GoogleSatelliteImageService: max_supp_zoom or null
alt NoTileAreaService response is not null
    GoogleSatelliteImageService --> Client: max_supp_zoom from NoTileAreaService
else
    GoogleSatelliteImageService --> Client: max_supp_zoom from MaxZoomService
end

@enduml