@startuml

Client -> GoogleSatelliteImageService: getCopyright
GoogleSatelliteImageService -> SessionContextProvider: get google session token
SessionContextProvider --> GoogleSatelliteImageService: token
GoogleSatelliteImageService -> GoogleMapsTileService: getViewPortInfo
GoogleMapsTileService -> GoogleMapsTileService: call Google Api for viewPort
note right: viewPort contains copyrights\nfor a given coordinates
GoogleMapsTileService --> GoogleSatelliteImageService: Google Api response = viewPort or error
alt Google Api respond with viewPort
    GoogleSatelliteImageService --> Client: copyright
    note right: copyright object is created from viewPort body.
    GoogleSatelliteImageService --> Client: copyright
else Google Api respond with error
    GoogleSatelliteImageService -> ExceptionUtils: map error from Google api to SipException
    ExceptionUtils --> GoogleSatelliteImageService: sipException
    GoogleSatelliteImageService --> Client: sipException
end

@enduml