@startuml CompressionHandler.compress

!$inputResource = "[inputResource]"
!$compressedResource = "[compressedResource]"

Client -> CompressionHandler: compress(format, qualityLevel, $inputResource)

CompressionHandler -> CompressionHandler: get effective quality level

alt $inputResource is not null

    alt qualityLevel < 0 || qualityLevel > MAX_QUALITY_LEVEL
        CompressionHandler --> Client: throw InvalidQualityLevelException
    end

    alt effectiveQualityLevel = MAX_QUALITY_LEVEL OR $inputResource = null
        CompressionHandler --> Client: $inputResource
    else
        alt no compression service configured for resource format
            CompressionHandler --> Client: throw FormatNotSupportedException
        end
        CompressionHandler -> JpegCompressionService: compress(Resource $inputResource, int effectiveQualityLevel)
        JpegCompressionService --> CompressionHandler: $compressedResource
        CompressionHandler --> Client: $compressedResource
    end

else
    CompressionHandler --> Client: null: Resource
end

@enduml