@startuml CopyrightHeaderEncodingTileServiceDecorator.getTile

Client -> CopyrightHeaderEncodingTileServiceDecorator: getTile(TileRequest tileRequest)

CopyrightHeaderEncodingTileServiceDecorator -> TileService: getTile(TileRequest tileRequest)
TileService -> CopyrightHeaderEncodingTileServiceDecorator: [tileServiceResponse]: Mono<ResponseEntity<Resource>>

alt there are copyright in TileService response headers
    CopyrightHeaderEncodingTileServiceDecorator -> CopyrightHeaderEncodingTileServiceDecorator: encode copyright headers
    CopyrightHeaderEncodingTileServiceDecorator -> CopyrightHeaderEncodingTileServiceDecorator: add tile from TileService to response
    CopyrightHeaderEncodingTileServiceDecorator --> Client: response: Mono<ResponseEntity<Resource>>
else
    CopyrightHeaderEncodingTileServiceDecorator --> Client: [tileServiceResponse] - Unchanged response from TileService
end

@enduml