@startuml

!$tileRequest = "[tileRequest]"

Client -> SatelliteImageProxyImpl: getTile(version, zoom, x, y, ifNoneMatch, format, region, qualityLevel, language, exchange)
alt api version is incorrect
    SatelliteImageProxyImpl --> Client: throws VersionNotSupportedException
end
alt image format not supported
    SatelliteImageProxyImpl --> Client: throws FormatNotSupportedException
end
SatelliteImageProxyImpl -> SatelliteImageProxyImpl: build $tileRequest from provided parameters
SatelliteImageProxyImpl -> TileService: getTile($tileRequest)
TileService --> SatelliteImageProxyImpl: Mono<ResponseEntity<Resource>>
SatelliteImageProxyImpl --> Client: Mono<ResponseEntity<Resource>>

@enduml