:resources: SatelliteImageProxyServiceDetailedDesign_resources

:doctype: book
:toc: left
:toclevels: 2
:numbered:
:encoding: 'utf-8'

=== Behavioral Design

This document will consider Satellite Image Proxy as the software
component and java classes as software units.

==== Unit interfaces

===== com.tomtom.puas.sip.SatelliteImageProxyImpl

Main class which is input of application. Methods of the class handles rest endpoint requests.

===== Mono<ResponseEntity<Resource>> getTile(String version, Integer zoom, Integer x, Integer y, String ifNoneMatch, String format, String region, Integer qualityLevel, String language, ServerWebExchange exchange)

Implementation for rest endpoint: GET /sip/{version}/tile/{z}/{x}/{y}
Get a satellite image tile specified by zoom level, x and y coordinates. Retrieving tile is delegated to class implementing _TileService_ interface.
Method proceeds as follows:

1. Verifies _version_ parameter against current api version. Throws _VersionNotSupportedException_ if they don't match.
2. Verifies requested tile image format. Throws _FormatNotSupportedException_ if format is not supported. Currently, only supported format is _jpeg_.
3. Delegates tile image retrieval to _TileService_ implementation class and returns result without changes.

image::{resources}/behaviour_diagrams/sip/SatelliteImageProxyImpl_getTile.svg[]
_SatelliteImageProxyImpl.getTile_

*Parameters*

- version (String) - The version of the service to call. (required)
- z (Integer) - Zoom level of the tile to be rendered. (required)
- x (Integer) - The x coordinate of the tile on a zoom grid. Values 0..2^(z-1). (required)
- y (Integer) - The y coordinate of the tile on a zoom grid. Values 0..2^(z-1). (required)
- ifNoneMatch (String) - Contains an identifier for a specific version of resource. The server will send back the requested resource, with a 200 HTTP status code, only if it doesn&#39;t have an ETag matching the given one. Otherwise, a 304 HTTP status code will be returned to indicate that content is not changed. (optional)
- format (String) - The format of the Response. (optional, default to jpeg)
- region (String) - A CLDR region identifier representing the physical location of the user. e.g. KR for South Korea. This parameter will be used to choose the appropriate backend content provider. If this parameter is not specified or is invalid, the default backend content provider will be used. (optional)
- qualityLevel (Integer) - A percentage value indicating the desired quality of image. Lower the quality-level, the more compressed the image. A factor of 100 will return the original image without any compression by SIP. Compression by SIP may be limited by the quality of the original image. for example jpeg images from Google are already at 90-95% jpeg-quality and compressing it again using same or bigger quality-level will not result in any compression. (optional)
- language (Integer) - A CLDR language identifier indicating the language information. For example, en-US or ja-JP. (optional, default to 'en-US')
- exchange (ServerWebExchange) - injected by framework

*Return* (Mono<ResponseEntity<Resource>>)

Http response with tile image resource. Status code and headers are set by _TileService_ and returned unchanged to client.

*Throws*

- _VersionNotSupportedException_ if version provided in request doesn't match current api version.
- _FormatNotSupportedException_ if requested tile format is not supported. Currently, only supported format is _jpeg_.

_[Req-SIP-10]_

===== Mono<ResponseEntity<Copyright>> getCopyright(String version, Float north, Float south, Float east, Float west, Integer zoom, String ifNoneMatch, String language, String region, ServerWebExchange exchange)

Implementation for rest endpoint: GET /sip/{version}/copyright/
Get copyright text for the specified area.
Method proceeds as follows:

1. Verifies _version_ parameter against current api version. Throws _VersionNotSupportedException_ if they don't match.
2. Delegates copyright retrieval to _CopyrightService_ result without changes.

*Parameters*

- version (String) - The version of the service to call. (required).
- north (Float) - The furthest north point in the viewport expressed in degrees. North must be in the range (-90,90). (required)
- south (Float) - The furthest south point in the viewport expressed in degrees. South must be in the range (-90,90). (required)
- east (Float) - The furthest east point in the viewport expressed in degrees. East must be in the range (-180,180). (required)
- west (Float) - The furthest west point in the viewport expressed in degrees. West must be in the range (-180,180). (required)
- zoom (Integer) - This is the current zoom level of the viewport. (required)
- ifNoneMatch (String) - Contains an identifier for a specific version of resource. The server will send back the requested resource, with a 200 HTTP status code, only if it doesn't have an ETag matching the given one. Otherwise, a 304 HTTP status code will be returned to indicate that content is not changed. (optional)
- language (String) - A CLDR language identifier indicating the language information. For example, en-US or ja-JP. (optional, default to 'en-US')
- region (String) - A CLDR region identifier representing the physical location of the user. e.g. KR for South Korea. This parameter will be used to choose the appropriate backend content provider. If this parameter is not specified or is invalid, the default backend content provider will be used. (optional)
- exchange (ServerWebExchange) - injected by framework.

*Returns* (Mono<ResponseEntity<Copyright>>)

Return the copyright text for the specified area. Status code and headers are set by _CopyrightService_ and returned unchanged to client.

*Throws*

_VersionNotSupportedException_ if "version" parameter doesn't match currently called api.

_[Req-SIP-11]_

===== Mono<ResponseEntity<Metadata>> getMetadata(String version, String region, ServerWebExchange exchange)

Implementation for rest endpoint: GET /sip/{version}/metadata
Get metadata info by given map provider in the requested region.
Method proceeds as follows:

1. Verifies _version_ parameter against current api version. Throws _VersionNotSupportedException_ if they don't match.
2. Delegates copyright retrieval to _MetadataService_ result without changes.

*Parameters*

- version (String) The version of the service to call. (required)
- region (String) A CLDR region identifier representing the physical location of the user. e.g. KR for South Korea. This parameter will be used to choose the appropriate backend content provider. If this parameter is not specified or is invalid, the default backend content provider will be used. (optional)
- exchange (ServerWebExchange) - injected by framework.

*Returns* (Mono<ResponseEntity<Metadata>>)

Returns metadata info for the given parameters. Status code and headers are set by _MetadataService_ and returned unchanged to client.

*Throws*
__VersionNotSupportedException__ if "version" parameter doesn't match currently called api.

_[Req-SIP-12]_

===== com.tomtom.puas.sip.service.BasicTileService
===== Mono<ResponseEntity<Resource>> getTile(TileRequest tileRequest)
Responsible for retrieving tile image and copyright from external service (Google) and send data back to client. Uses _GoogleSatelliteImageService_ to get tiles from google service.
If _GoogleSatelliteImageService_ returns _Mono<SipException>_, then this method will throw _SipException_ as well.

image::{resources}/behaviour_diagrams/service/BasicTileService_getTile.svg[]
_BasicTileService.getTile_

*Parameters*

- TileRequest - object containing all information needed to make request to google for tiles: coordinates, eTag, format, qualityLevel, mapProvider, language.

*Returns* (Mono<ResponseEntity<Resource>>)

_ResponseEntity_ containing tile image data as a spring _Resource_. _ResponseEntity_ object is created by _GoogleSatelliteImageService_ and return to the client in unchanged with regard to http response body, header and status.

*Throws*

_SipException_ if _GoogleSatelliteImageService_ returns _Mono<SipException>_.

_[Req-SIP-1]_

===== com.tomtom.puas.sip.service.CachingTileServiceDecorator
===== Mono<ResponseEntity<Resource>> getTile(TileRequest tileRequest)
Responsible for retrieving tile image and copyright from cache or external service (google), and then add it to cache if not present.

image::{resources}/behaviour_diagrams/service/CachingTileServiceDecorator_getTile.svg[]
_CachingTileServiceDecorator.getTile_

Expiry time of a tile is stored in cache in tile metadata and returned to client as a http response header. Expiry time of a new tile (not in cache yet) is calculated
from google api response base in fields:
1. _max-age_ - currentTime + _max-age_.
2. if _max-age_ not present, then uses _Expiry_ field.

*Parameters*

- TileRequest - object containing all information needed to make request to google for tiles: coordinates, eTag, format, qualityLevel, mapProvider, language.

*Returns* (Mono<ResponseEntity<Resource>>)

_ResponseEntity_ containing tile image data as a spring _Resource_.

*Throws*

_SipException_ if _GoogleSatelliteImageService_ returns _Mono<SipException>_.

_[Req-SIP-2]_

===== com.tomtom.puas.sip.service.CopyrightHeaderEncodingTileServiceDecorator
===== Mono<ResponseEntity<Resource>> getTile(TileRequest tileRequest)
Responsible for retrieving tile image and copyright from cache or external service (google).
If _TileService_ returns data, then encode copyright headers before sending back to service client. Otherwise, method returns unchanged response from _TileService_.

image::{resources}/behaviour_diagrams/service/CopyrightHeaderEncodingTileServiceDecorator_getTile.svg[]
_CopyrightHeaderEncodingTileServiceDecorator.getTile_

*Parameters*

- TileRequest - object containing all information needed to make request to google for tiles: coordinates, eTag, format, qualityLevel, mapProvider, language.

*Returns* (Mono<ResponseEntity<Resource>>)

Copyright data.

_[Req-SIP-9]_

===== com.tomtom.puas.sip.components.compression.CompressionHandler
===== Resource compress(String format, Integer qualityLevel, Resource resource)CompressionHandler
Compresses image resource with given quality level and format.

image::{resources}/behaviour_diagrams/compression/CompressionHandler_compress.svg[]
_CompressionHandler.compress_

*Parameters*

- format - image format.
- qualityLevel - quality level of image in resource.
- resource - image resource to compress.

*Returns* (Resource)

Compressed resource image. null if input resource was null;

_[Req-SIP-3]_

===== boolean isDefaultQualityLevel(Integer qualityLevel)

Checks if quality level has default value.

*Parameters*

- qualityLevel: int - Quality level of compression

*Returns* (boolean)

'True' if 'qualityLevel' is null or is equal to default value, otherwise returns 'False'.
Default quality level is set in application configuration.

_[Req-SIP-4]_

===== com.tomtom.puas.sip.components.cache.TileCache
===== Mono<TileMetadata> getMetadata(TileCoordinates coordinates, String format, String mapProvider)

Retrieves tile metadata from application cache by delegating 'get' operation to _TileMetadataRepository_ instance.

*Parameters*

- coordinates (TileCoordinates) - Coordinates of a tile for which metadata was stored. Is a part of cache key string.
- format (String) - Format of a cached image. Is a part of cache key string.
- mapProvider (String) - name of external service providing map images (e.g.: google). Is a part of cache key string.

*Returns* (Mono<TileMetadata>)

TileMetadata object retrieved by repository. Response is wrapped in Reactor _Mono_ object for further stream processing.
Returns empty _Mono_ if no data was found by _TileMetadataRepository_.

_[Req-SIP-5]_

===== Mono<Resource> getTile(TileCoordinates coordinates, String format, String mapProvider)
Retrieves tile from application cache by delegating 'get' operation to _TileImageRepository_ instance.

*Parameters*

- coordinates (TileCoordinates) - Coordinates of a tile. Is a part of cache key string.
- format (String) - Format of a cached image. Is a part of cache key string.
- mapProvider (String) - name of external service providing map images (e.g.: google). Is a part of cache key string.

*Returns* (Mono<Resource>)

Spring _Resource_ object with cached tile image. Response is wrapped in Reactor _Mono_ object for further stream processing.
Returns empty _Mono_ if no data was found by _TileMetadataRepository_.

_[Req-SIP-6]_

===== Mono<Void> storeTile(TileCoordinates coordinates, String format, String mapProvider,String language, ResponseEntity<Resource> response)

Store tiles and metadata for a tile in cache by delegating 'store' operation to _TileMetadataRepository_ and _TileImageRepository_.
If storing metadata fails with exception then it will not store the tile.

*Parameters*

- coordinates (TileCoordinates) - Coordinates of a tile for which metadata was stored. Is a part of cache key string.
- format (String) - Format of a cached image. Is a part of cache key string.
- mapProvider (String) - name of external service providing map images (e.g.: google). Is a part of cache key string.
- language (String) - tile language.
- response (ResponseEntity<Resource>) - object represents http response. It contains tile resource in body and copyrights in headers to be cached.

*Returns* (Mono<Viod>)

Empty _Mono_ object.

*Throws*

_RuntimeException_ if _TileMetadataRepository_ or _TileImageRepository_ throw exception when storing data.

_[Req-SIP-7]_

===== Mono<Void> updateMetadata(TileMetadata tileMetadata)
Updates existing metadata in cache by delegating 'put' operation to _TileMetadataRepository_ instance.

*Parameters*

- tileMetadata (TileMetadata) - metadata object to update in cache. by delegating to cache repositories injected to TileCache instance.

*Returns* (Mono<Viod>)

Empty _Mono_ object.

_[Req-SIP-8]_

===== com.tomtom.puas.sip.components.cache.inmemory.InMemorySecondLevelCache

Class is a responsible for managing communication with in-memory application cache.

===== Mono<Session> put(SessionCacheKey sessionCacheKey, Session session)

Stores google session token in in-memory application cache.

*Parameters*

- sessionCacheKey (SessionCacheKey) - Cache key which identifies record in cache.
- session (Session) - Session object to store in cache. Object wraps google token string.

*Returns* (Mono<Session>)

Stored session object.

_[Req-SIP-13]_

===== Mono<Session> get(SessionCacheKey sessionCacheKey)
Retrieves google session token object from in-memory cache.

*Parameters*

- sessionCacheKey (SessionCacheKey) - Cache key which identifies record in cache to retrieve.

*Returns* (Mono<Session>)

Retrieved session object wrapped in _Mono_. If no session was found under given key returns empty _Mono_.

_[Req-SIP-14]_

===== com.tomtom.puas.sip.components.cache.redis.SecondLevelCacheImpl

===== Mono<Session> put(SessionCacheKey sessionCacheKey, Session session)
Stores google session token in 2nd level cache. Operation is delegated to _RedisSessionRepository_.

*Parameters*

- sessionCacheKey (SessionCacheKey) - Cache key which identifies record in cache.
- session (Session) - Session object to store in cache. Object wraps token string.

*Returns* (Mono<Session>)

Session object returned by _RedisSessionRepository.put_.

_[Req-SIP-16]_

===== Mono<Session> get(SessionCacheKey sessionCacheKey)

Retrieves session object from 2nd level cache. Operation is delegated to _RedisSessionRepository_.

*Parameters*

- sessionCacheKey (SessionCacheKey) - Cache key which identifies record in cache to retrieve.

*Returns* (Mono<Session>)

Retrieved session object wrapped in _Mono_. If no session was found under given key then returns empty _Mono_.

_[Req-SIP-17]_

===== Flux<Tuple2<String, Session>> getSessionKeys()
Retrieves all session objects stored in 2nd level application cache with their cache keys. Operation is delegated to _RedisSessionRepository_.

*Returns* (Flux<Tuple2<String, Session>>)

All session objects stored in 2nd level application cache.

_[Req-SIP-18]_

===== com.tomtom.puas.sip.components.cache.redis.RedisSessionRepository

===== Mono<Session> put(SessionCacheKey sessionCacheKey, Session session)

Stores or updates google session object in 2nd level cache under given key.

*Parameters*

- sessionCacheKey (SessionCacheKey) - Cache key which identifies record in cache.
- session (Session) - Session object to store in cache. Object wraps token string.

*Returns* (Mono<Session>)

Stored session object.

_[Req-SIP-19]_

===== Mono<Session> get(SessionCacheKey sessionCacheKey)

Retrieves session object from 2nd level cache.

*Parameters*

- sessionCacheKey (SessionCacheKey) - Cache key which identifies record in cache to retrieve.

*Returns* (Mono<Session>)

Retrieved session object wrapped in _Mono_ or empty _Mono_ if no session was found under given key.

_[Req-SIP-20]_

===== Flux<Tuple2<String, Session>> getSessionKeys()
Retrieves all session objects stored in 2nd level application cache with their cache keys.

*Returns* (Flux<Tuple2<String, Session>>)
Gets all session objects stored in 2nd level application cache with their cache keys.

_[Req-SIP-21]_

===== com.tomtom.puas.sip.components.google.utils.TileCoordinatesUtils

===== static Point centralPoint(TileCoordinates tileCoordinates)

Calculates geographical coordinates (latitude and longitude) for central point in tile.

*Parameters*

- tileCoordinates - _TileCoordinates_ object representing tile to transform.

*Returns* (Point)

_Point_ representing coordinates of central point.

_[Req-SIP-23]_

===== public static boolean outOfRange(TileCoordinates tileCoordinates)

Checks if x or y coordinates are within range possible for given zoom.

*Parameters*

- tileCoordinates - _TileCoordinates_ object representing tile to verify.

*Returns* (boolean)

'true' if x, y coordinates are within the range, 'false' otherwise.

_[Req-SIP-70]_

===== static Double south(TileCoordinates tileCoordinates)
Calculates latitude for south edge of given tile.

*Parameters*

- tileCoordinates (TileCoordinates) - coordinates of tile in degrees.

*Returns* (Double)

Latitude value of south edge of given tile.

_[Req-SIP-24]_

===== static Double north(TileCoordinates tileCoordinates)
Calculates latitude for north edge of given tile.

*Parameters*

- tileCoordinates (TileCoordinates) - coordinates of tile in degrees.

*Returns* (Double)

Latitude value of north edge of given tile.

_[Req-SIP-25]_

===== static Double east(TileCoordinates tileCoordinates)
Calculates longitude for east edge of given tile.

*Parameters*

- tileCoordinates (TileCoordinates) - coordinates of tile in degrees.

*Returns* (Double)

Longitude value of east edge of given tile.

_[Req-SIP-26]_

===== static Double west(TileCoordinates tileCoordinates)
Calculates longitude for west edge of given tile.

*Parameters*

- tileCoordinates (TileCoordinates) - coordinates of tile in degrees.

*Returns* (Double)

Longitude value of west edge of given tile.

_[Req-SIP-27]_

===== com.tomtom.puas.sip.components.cache.inmemory.InMemoryTileImageRepository

===== Mono<Resource> get(TileCoordinates coordinates, String format, String mapProvider)
Retrieves satellite image tile from in-memory cache.

*Parameters*

- coordinates (TileCoordinates) - of tile to get
- format (String) - image format of tile file
- mapProvider (String) - map provider that should be used (e.g.: google)

*Returns* (Mono<Resource>)

Resource that contains tile image. Returns empty _Mono_ when no tile is found in cache under given key.

_[Req-SIP-28]_

===== Mono<Void> put(TileCoordinates coordinates, String format, String mapProvider, Resource resource, Duration ttl)
Updates satellite image tile in in-memory cache. If tile does not exist, creates new one.

*Parameters*

- coordinates (TileCoordinates) - of tile to get
- format (String) - image format of tile file
- mapProvider (String) - map provider that was used to get given tile
- resource (Resource) - represents tile to store
- ttl (Duration) - time-to-live value for given image (might be ignored by cache implementation)

*Returns* (Mono<Void>)

Empty _Mono_. If 'put' operation throws _Exception_, then _Mono_ with error is returned.

_[Req-SIP-29]_

===== com.tomtom.puas.sip.components.cache.inmemory.InMemoryTileMetadataRepository

===== Mono<TileMetadata> get(TileCoordinates tileCoordinates, String format, String mapProvider)

Retrieves metadata for tile that matches given criteria from in-memory cache.

*Parameters*

- coordinates (TileCoordinates) - of tile metadata to get
- format (String) - image format of tile metadata file
- mapProvider (String) - map provider that should be used (e.g.: google)

*Returns* (Mono<TileMetadata>)

Round metadata or empty _Mono_ if tile for given criteria does not exist.

_[Req-SIP-30]_

===== Mono<Void> put(TileMetadata tileMetadata)

Updated metadata for tile that matches given criteria in in-memory cache. Creates new entry if none data exists.

*Parameters*

- tileMetadata (TileMetadata) - metadata object to update in cache

*Returns* (Mono<Void>)

Empty _Mono_.

_[Req-SIP-31]_

===== com.tomtom.puas.sip.components.cache.redis.RedisTileImageRepository

===== Mono<Resource> get(TileCoordinates coordinates, String format, String mapProvider)
Retrieves satellite image tile from 2nd level cache. Method doesn't throw exception on cache operation error, logs error message instead.

*Parameters*

- coordinates (TileCoordinates) - coordinates of tile to retrieve.
- format (String) - image format of tile file
- mapProvider (String) - map provider that should be used (e.g.: google)

*Returns* (Mono<Resource>)

Resource that contains tile image. Returns empty _Mono_ if no tile was found in cache or exception was thrown during cache operation.

_[Req-SIP-32]_

===== Mono<Void> put(TileCoordinates coordinates, String format, String mapProvider, Resource resource, Duration ttl)
Updates satellite image tile in 2nd level cache. If tile does not exist, creates new one. Method doesn't throw exception on cache operation error, logs error message instead.

*Parameters*

- coordinates (TileCoordinates) - coordinates of tile.
- format (String) - image format of tile file.
- mapProvider (String) - map provider that was used to get given tile.
- resource (Resource) - represents tile to store.
- ttl (Duration) - time-to-live defines how cache record will be valid.

*Returns* (Mono<Void>)

Empty _Mono_ or exception was thrown during cache operation.

_[Req-SIP-33]_

===== com.tomtom.puas.sip.components.cache.redis.RedisTileMetadataRepository

===== Mono<TileMetadata> get(TileCoordinates tileCoordinates, String format, String mapProvider)

Retrieves metadata for tile that matches given criteria from 2nd level cache. Method doesn't throw exception on cache operation error, logs error message instead.

*Parameters*

- coordinates (TileCoordinates) - of tile metadata.
- format (String) - image format of tile metadata file.
- mapProvider (String) - map provider that should be used (e.g.: google).

*Returns* (Mono<TileMetadata>)

Round metadata .Returns empty _Mono_ if tile for given criteria does not exist or exception was thrown during cache operation.

_[Req-SIP-34]_

===== Mono<Void> put(TileMetadata tileMetadata)

Updated metadata for tile that matches given criteria in 2nd level cache. Create new entry if no record under given key exists in cache. Method doesn't throw exception on cache operation error, logs error message instead.

*Parameters*

- tileMetadata (TileMetadata) - metadata object to store or update in cache.

*Returns* (Mono<Void>)

Empty _Mono_ or exception was thrown during cache operation.

_[Req-SIP-35]_

===== com.tomtom.puas.sip.components.google.service.impl.DefaultNoTileAreaService

Sip service is collection information about areas of the world which don't have Google tile for a given zoom - no-tile area.
When tile for such area is requested by the client, Sip stores information about the missing tile in cache. Cache entry contains information about position of the area and max available zoom for it.
More information about no-tile areas can be found link:https://confluence.tomtomgroup.com/x/ccVKN[here].

===== Mono<Void> cacheNoTileArea(TileCoordinates tileCoordinates, String format)
Method stores information about no-tile area in cache for given coordinates and image format. Sip also searches for other no-tile areas around the given coordinates and store them as well.

*Parameters*

- tileCoordinates (TileCoordinates) - coordinates of area without tile.
- format (String) - format of tile image.

*Returns* (Mono<Void>)

Empty _Mono_.

_[Req-SIP-36]_

===== Mono<Integer> getMaxSupportedZoom(TileCoordinates tileCoordinates)
Method finds and returns the highest available zoom value for given coordinates.

*Parameters*

- tileCoordinates (TileCoordinates) - coordinates of area without tile.
- format (String) - format of tile image.

*Returns* (Mono<Integer>)

_Mono_ with the highest available zoom value for given tile coordinates.

_[Req-SIP-71]_

===== com.tomtom.puas.sip.components.cache.redis.RedisNoTileAreaRepository

===== Mono<Void> create(TileCoordinates northWest, TileCoordinates southEast, long ttl)
Stores entry for new no tile area using coordinates as cache key. No-tile area is spread over more than one tile. The entire to-tile region is described with coordinates of corner tiles of the region.

*Parameters*

- northWest (TileCoordinates) - coordinates that describes north-west corner point of no-tile rectangle.
- southEast (TileCoordinates) - coordinates that describes south-east corner point of no-tile rectangle.

*Returns* (Mono<Void>)

Empty _Mono_ or _Mono_ error if exception was thrown on Redis operation.

_[Req-SIP-38]_

===== Mono<Integer> findMinNotSupportedZoom(TileCoordinates tileCoordinates)
Gets the value of zoom for area with the lowest zoom that contains given coordinates. No-tile areas are caches only for certain range of supported zoom values. The range starts with _min_supported_zoom_ value defined in application config.

- tileCoordinates (TileCoordinates) - coordinates of a tile.

*Returns* (Mono<Integer>)

Returns minimal zoom value for given coordinates.
Returns empty _Mono_ if:
- no no-tile area found in cache,
- requested zoom is lower than _min_supported_zoom_,
- requested no-tile area coordinates are expired in cache,
Returns _Mono_ error if exception is thrown during Redis operation.

_[Req-SIP-39]_

===== boolean active()
Checks if _CircuitBreaker_ is opened.

*Returns*

'true' if _CircuitBreaker_ is opened, 'false' otherwise.

_[Req-SIP-72]_

===== com.tomtom.puas.sip.monitoring.TracingIdFilter

===== Mono<Void> filter(ServerWebExchange ex, WebFilterChain chain)
Process the Web request and (optionally) delegate to the next _WebFilter_ through the given _WebFilterChain_. Method adds 'traceId' key _ex_ object if 'x-b3-traceid' was provided in it.
If 'x-b3-traceid' header is not in request, then _ex_ remains unchanged.

*Parameters*

- ex (WebFilter) - the current server exchange object - context of incoming requests.
- chain (WebFilter) - provides a way to delegate to the next filter

*Returns* (Mono<Void>)

To indicate when request processing is complete. Method returns when filter chain is completed.

_[Req-SIP-40]_

===== com.tomtom.puas.sip.components.google.utils.ExceptionUtils

===== static String maskSensitive(String msg)
Hides sensitive information in message by replacing then with '***'. Method looks for strings starting with: ["session=", "key="] and ending with: [";|&| |session=|key=|$|\n"].
Everything between start and end strings is replaced with '***'.

*Parameters*

- msg (String) - string with potentially sensitive information.

*Returns* (String)

String with sensitive information replaced with '***'.

_[Req-SIP-68]_

===== static String getMessageAndStacktrace(Throwable e)
Converts exception to a single string out of exception message and exception stacktrace. Method uses _maskSensitive()_ to hide sensitive information in entire composed string.

*Parameters*

- e (Throwable) - exception to be converted into single string message.

*Returns* (String)

String composed of exception message and exception stacktrace.

_[Req-SIP-69]_

===== static RuntimeException getSipException(WebClientResponseException.NotFound exception, int requestedZoom, int maxZoom)
Maps input _exception_ parameter to _RuntimeException_.

*Parameters*

- exception (WebClientResponseException.NotFound) - exception to map.
- requestedZoom (int) - zoom value.
- maxZoom (int) - zoom value.

*Returns* (RuntimeException)

If _requestedZoom_ > _maxZoom_, then return _ZoomOutOfRangeException_.
Otherwise, call _getSipException(WebClientResponseException exception)_ and return result.

_[Req-SIP-77]_

===== static SipException getSipException(WebClientResponseException exception)

Handles exceptions thrown by rest client during calls to external services like Google Api.
It takes _WebClientResponseException_ exceptions and maps it into custom Sip application exception. _WebClientResponseException_ contains fields like response body and error reason which are used for mapping.

*Parameters*

- exception (WebClientResponseException) - exception to map.

*Returns* (SipException)

Sip custom exception mapped from input exception according to below table. Custom exception has error code and message set based on input exception.

|===
| *Input exception reason* | *SipException* | *statusCode* | *errorCode*
| notFound              | InvalidParamsException        | 404 | 30003
| notFound              | InvalidParamsException        | 404 | 30003
| required              | RetryLaterException           | 429 | 40001
| badRequest            | RetryLaterException           | 429 | 40004
| quotaExceeded         | RetryLaterException           | 429 | 40005
| rateLimitExceeded     | RetryLaterException           | 429 | 40006
| authTokenExpired      | RetryLaterException           | 429 | 40003
| invalidCredentials    | InvalidCredentialsException   | 500 | 40002
| Unknown or non reason / missing response body | UnknownErrorResponseException | 500 | 30005
|===

*Throws*

UnknownErrorResponseException when response body has incorrect format. Format must match mapping class _com.tomtom.puas.sip.components.google.model.ErrorResponse_.

_[Req-SIP-41]_

===== static boolean isSessionInvalidOrExpiredException(WebClientResponseException exception)
Checks reason of input _exception_.

*Parameter*

- exception (WebClientResponseException) - exception to check.

*Returns* (boolean)

'true' if reason of exception is 'authTokenExpired' or 'invalidCredentials'. 'false' otherwise.

_[Req-SIP-76]_

===== static void logExceptionInfo(Throwable e, Logger log)
Prevent logging exceptions of types: _RedisConnectionFailureException_, _CallNotPermittedException_, _RedisCommandTimeoutException_. Logs every other exception.

*Parameter*

- e (Throwable) - exception to log.
- log (Logger) - logger.

*Returns* (void)

_[Req-SIP-74]_

===== static RuntimeException googleUnreachableException()

*Returns* (RetryLaterException)

Returns _RetryLaterException_ with statusCode=429 and errorCode=50001

_[Req-SIP-75]_

===== com.tomtom.puas.sip.model.CacheControlDetails

Class holds information about tile cache entry, e.g. expiration date. It is a part as TileMetadata object which defines.

===== CacheControl toCacheControl()
Create new _CacheControl_ object from current _CacheControlDetails_ instance. _CacheControl_ holds information about tile cache entry which are added to response header.

*Returns* (CacheControl)
New _CacheControl_ instance.

_[Req-SIP-44]_

===== Duration getTtl()
Checks time between _now_ and expiration time of _CacheControlDetails_ instance.

*Returns* (Duration)
Time between _now_ and expiration time of _CacheControlDetails_ instance.

_[Req-SIP-45]_

===== static CacheControlDetails of(ResponseEntity<?> response)
Creates new instance of _CacheControlDetails_ from input _ResponseEntity_.
_CacheControlDetails_ defines expiration date property which is calculated based on:
- First 'max-age' header value,
- If 'max-age' is not present, then 'Expires' value is used.

*Parameters*

- response (ResponseEntity) - input for _CacheControlDetails_ instance creation.

*Returns* (CacheControlDetails)

New instance of _CacheControlDetails_.

_[Req-SIP-46]_

===== com.tomtom.puas.sip.model.NoTileAreaCoordinates

===== static NoTileAreaCoordinates of(TileCoordinates northWestCoordinates, TileCoordinates southEastCoordinates)

Creates new instance of _NoTileAreaCoordinates_ class from given coordinates.

*Parameters*

- northWestCoordinates (TileCoordinates) - input coordinates for _NoTileAreaCoordinates_ instance creation.
- southEastCoordinates (TileCoordinates) - input coordinates for _NoTileAreaCoordinates_ instance creation.

*Returns* (NoTileAreaCoordinates)

New instance of _NoTileAreaCoordinates_ class.

*Throws*

_IllegalArgumentException_ when zooms of northWestCoordinates and southEastCoordinates are not equal.

_[Req-SIP-47]_

===== boolean contains(TileCoordinates tileCoordinates)

Check if no-tile area contains given tile coordinate. Method gets central point of _tileCoordinates_ parameter and checks if this point is located within rectangle of current no-tile area.

*Parameters*

- tileCoordinates (TileCoordinates) - tile coordinates.

*Returns* (boolean)

'true' if no-tile area contains given tile coordinate, 'false' otherwise.

_[Req-SIP-73]_

===== com.tomtom.puas.sip.components.cache.inmemory.InMemoryNoTileAreaRepository

===== Mono<Void> create(TileCoordinates northWest, TileCoordinates southEast, long ttl)
Stores entry for new no tile area using coordinates as cache key.

*Parameters*

- northWest (TileCoordinates) - coordinates that describes north-west corner point of no-tile area rectangle.
- southEast (TileCoordinates) - coordinates that describes south-east corner point of no-tile area rectangle.

*Returns* (Mono<Void>)

Empty _Mono_.

_[Req-SIP-49]_

===== Mono<Integer> findMinNotSupportedZoom(TileCoordinates tileCoordinates)
Finds lowest not supported zoom for given tile coordinates. Minimal not supported zoom is the lowest zoom value stored in to-tile cache for given coordinates.

- tileCoordinates (TileCoordinates) - tiles coordinates.

*Returns* (Mono<Integer>)

Min zoom value stored in to-tile cache for given coordinates. Empty _Mono_ there are no cache entry for given coordinates.

_[Req-SIP-50]_

===== com.tomtom.puas.sip.components.google.service.impl.DefaultGoogleMapsTileService

===== Mono<ResponseEntity<Resource>> getTile(TileCoordinates tileCoordinates, String ifNoneMatch,  SessionKey sessionKey)
Retrieves tile image by calling google api over http request.

image::{resources}/behaviour_diagrams/google_service/DefaultGoogleMapsTileService_getTile.svg[]
_DefaultGoogleMapsTileService.getTile - Get tile from google api_

*Parameters*

- tileCoordinates (TileCoordinates) - tiles coordinates.
- String ifNoneMatch - value for request header 'If-None-Match'. It is used to check if requested data was already downloaded.
                       If it is set and equal value in google api, then google sends '304 - not modified' status code in response.
- SessionKey sessionKey - api key used to authorize google requests.

*Returns* (Mono<ResponseEntity<Resource>>)

Tile image is returned resource when google api call finished successfully.
Successful http response should contain values like:
    - StatusCode = 'OK', +
    - Body = Image Bytes, +
    - Header - ContentType = 'image/jpeg', +
    - Header - ETag = valid etag value, the same as _ifNoneMatch_.+
Error _Mono_ is returned when google api returns error response. Response contains then _WebClientResponseException_ exception.

_[Req-SIP-51]_

===== Mono<Boolean> tileExists(TileCoordinates tileCoordinates, SessionKey sessionKey)
Checks if tile for given coordinates exist by calling google api over http request.

image::{resources}/behaviour_diagrams/google_service/DefaultGoogleMapsTileService_tileExists.svg[]
_DefaultGoogleMapsTileService.tileExists_

*Parameters*

- tileCoordinates (TileCoordinates) - tiles coordinates.
- SessionKey sessionKey - api key used to authorize google requests.

*Returns* (boolean)

'true' if tile with given coordinates is available to download from Google, 'false' otherwise.
This method returns _WebClientResponseException_ when response from google api is different from 'OK' (200) or 'NOT_FOUND' (404).

_[Req-SIP-52]_

===== Mono<ResponseEntity<Session>> createSession(String language, String format)
Gets new google session by calling google api over http request.

image::{resources}/behaviour_diagrams/google_service/DefaultGoogleMapsTileService_createSession.svg[]
_DefaultGoogleMapsTileService.createSession_

*Parameters*

- language (String) - language. It is required by google api to provide.
- format (String) - image format. It is required by google api to provide.

*Returns* (Mono<ResponseEntity<Session>>)

Session token key. The token is commonly provided by Google with expiry date in response. If expiry date is missing or invalid, Sip adds default one to Session object sets for 14 days.
When error is returned from Google Api, then it is returned to client as was received.

_[Req-SIP-53]_

===== Mono<ResponseEntity<ViewPortInfo>> getViewPortInfo(ViewPort viewPort, String ifNoneMatch, SessionKey sessionKey)
Gets view port information by calling google api over http request.

image::{resources}/behaviour_diagrams/google_service/DefaultGoogleMapsTileService_getViewPortInfo.svg[]
_DefaultGoogleMapsTileService.getViewPortInfo_

*Parameters*

- viewPort (ViewPort) - object which specifies area for which _ViewPortInfo_ should be downloaded. Object contains: zoom value and north, south, east, west coordinates.
- String ifNoneMatch - value for request header 'If-None-Match'. It is used to check if requested data was already downloaded.
                       If it is set and equal value in google api, then google sends '304 - not modified' status code in response.
- SessionKey sessionKey - api key used to authorize google requests.

*Returns* (Mono<ResponseEntity<ViewPortInfo>>)

When call is successful, then returns _ViewPortInfo_ which contains copyright for the given area. +
Successful http response should contain values like:
- StatusCode = 'OK', +
- Body = Image Bytes, +
- Header - ContentType = 'image/jpeg', +
- Header - ETag = valid etag value, the same as _ifNoneMatch_.+
Error _Mono_ is returned when google api returns error response. Response contains then _WebClientResponseException_ exception.

_[Req-SIP-54]_

===== Mono<Void> fallback(Exception e)
Handles exceptions thrown from methods in _DefaultGoogleMapsTileService_.

*Parameters*

- e (Exception) - thrown exception

*Returns* (Mono<T>)

429 'Too Many Requests' - if CallNotPermittedException or TimeoutException or CancellationException.
For every other type, returns input exception error.
429, Series.CLIENT_ERROR, "Too Many Requests"

_[Req-SIP-55]_

===== void cleanUp() throws Exception
Framework method used to finalizing service instance when server is shutdown.

_[Req-SIP-61]_

===== com.tomtom.puas.sip.exception.RestExceptionHandler

===== Mono<Void> handle(ServerWebExchange exchange, Throwable ex)
Handles globally exception thrown in application that wasn't caught.
Exception are further translated to http response codes according to below table:
|===
| SipException | Error code from SipException (additionally: If _ZoomOutOfRangeException_, Then Sets "x-max-zoom" header)
| ServerWebInputException | INVALID_REQUEST_FORMAT(40004)
| ResponseStatusException | INTERNAL_ERROR(30005)
| Other exceptions | Exception from _ex_ param
|===

Headers set in response:
'Content-Type': 'json'
x-max-zoom: <Integer> (if _ZoomOutOfRangeException_ was thrown)

*Parameters*

- ex (Exception) - input exception.
- exchange (ServerWebExchange) - object holding response date.

_[Req-SIP-56]_

===== com.tomtom.puas.sip.components.google.service.impl.DefaultMaxZoomService

===== Mono<Integer> getMaxSupportedZoom(TileCoordinates tileCoordinates)
Finds in max-zoom cache and return maximum zoom value supported for given coordinates.
Max zooms are cached in json files stored in Azure blob storage. The cache contains collection of file prefixed with _maxzoomrects_. Each file contains zooms for different part of the world.
At method at beginning downloads cache files from azure with 1 retry if download fails. It looks for files in configured directory with specified prefix. If directory contains other files, they will be ignored.
Each file contains list of entries like example below: +
{"z": 20, "n": 32.310791, "s": 31.98120110000002, "e": 13.084716700000001, "w": 12.919921799999997} +
where 'z' is zoom followed by degree coordinates of north, south, east, west edge of the area.

*Parameters*

- tileCoordinates (TileCoordinates) - tile coordinates.

*Returns* (Mono<Integer>)

Max supported maximum zoom value supported for given coordinates.
if max supported zoom is larger or equal then given zoom in _tileCoordinates_, then it returns _tileCoordinates.zoom_.
If no tiles for given area are present, then returns empty _Mono_.

_[Req-SIP-57]_

===== com.tomtom.puas.sip.components.google.service.impl.CachingSessionContextProvider

===== SessionContext sessionContext(String language, String format)
Create new _SessionContext_ object. _SessionContext_ contains google session token which can authorize Google Api calls made within this context.
Token is set in context either by retrieving it from cache 1st/2nd level, or by creating new one with Google Api request for new session token.

image::{resources}/behaviour_diagrams/google_service/CachingSessionContextProvider_sessionContext.svg[]
_CachingSessionContextProvider.sessionContext_

*Parameters*

- language (String) - language. It is required by google api to provide.
- format (String) - image format. It is required by google api to provide.

*Returns* (SessionContext)

Session token key. The token is commonly provided by Google with expiry date in response. If expiry date is missing or invalid, Sip adds default one to Session object sets for 14 days.

*Throws*

_WebClientResponseException_ when function executed within session context returned _Mono_ error with one of reasons: "invalidCredentials" or "authTokenExpired".

_[Req-SIP-59]_

===== com.tomtom.puas.sip.components.cache.cronjobs.SessionTokenUpdateCronjob

===== void updateSessionTokens()

Method is executed periodically and updates google session token saved in 2nd level cache if expiration time is less than given interval.

image::{resources}/behaviour_diagrams/cache/SessionTokenUpdateCronjob_updateSessionTokens.svg[]
_CachingSessionContextProvider.sessionContext_

_[Req-SIP-60]_

===== com.tomtom.puas.sip.model.TileCoordinates

===== TileCoordinates toLowerZoom(int lowerZoom)

Compares given lower zoom value with the instance zoom and returns the lower one.

*Parameters*

- lowerZoom (int) - zoom value.

*Returns* (TileCoordinates)

If instance zoom is lower than given, then instance of _TileCoordinates_ is returned unchanged.
if instance zoom is higher than given, then returns new instance on _TileCoordinates_ with _lowerZoom_ value and recalculated coordinates x, y.
Formula to recalculate coordinates: new_coordinate = current_coordinate / 2 ^ (current_zoom - lowerZoom).

_[Req-SIP-62]_

===== com.tomtom.puas.sip.components.google.service.impl.GoogleSatelliteImageService

===== Mono<ResponseEntity<Copyright>> getCopyright(ViewPort viewPort, String ifNoneMatch, String language)

Gets copyright information for area specified by _viewPort_ parameter.

image:{resources}/behaviour_diagrams/google_service/GoogleSatelliteImageService_getCopyright.svg[]
_GoogleSatelliteImageService.getCopyright_

*Parameters*

- viewPort - viewport for which copyright should be found.
- ifNoneMatch - identifier for a specific version of resource. Determines if this resource was already requested by client service.
- language - language identifier indicating the language information on the tile. If no language is specified, then default (en-US) one will be used.

*Returns*

Response entity that contains copyright information in body or error according to _ExceptionUtils.getSipException_ mapping.

_[Req-SIP-63]_

===== Mono<ResponseEntity<Metadata>> getMetadata()

Gets metadata information about coordinates system and projection typed used by service. This information has fixed values configured in application configuration.

*Returns* (Mono<ResponseEntity<Metadata>>)

Metadata information about coordinates system and projection typed used by service.

_[Req-SIP-64]_

===== Mono<ResponseEntity<Resource>> getTile(TileCoordinates tileCoordinates, String ifNoneMatch, String format)

Gets tile from Google Api for given coordinates.

image:{resources}/behaviour_diagrams/google_service/GoogleSatelliteImageService_getTile.svg[]
_GoogleSatelliteImageService.getTile_

*Parameters*

- tileCoordinates - coordinates which specifies requested tile.
- ifNoneMatch - identifier for a specific version of resource. Is used by Google Api to verify if requested resource was already downloaded.
- format - image format of tile file.

*Returns* (Mono<ResponseEntity<Resource>>)

Tile resource or exception according to _ExceptionUtils.getSipException_ mapping.

_[Req-SIP-65]_

===== Mono<Integer> getMaxSupportedZoom(TileCoordinates tileCoordinates)

Gat maximum supported value for given coordinates.

image:{resources}/behaviour_diagrams/google_service/GoogleSatelliteImageService_getMaxSupportedZoom.svg[]
_GoogleSatelliteImageService.getMaxSupportedZoom_

*Parameters*

- tileCoordinates (TileCoordinates) - tile coordinates.

*Returns* (Mono<Integer>)

Maximum supported zoom value.

_[Req-SIP-66]_

===== com.tomtom.puas.sip.components.compression.impl.JpegCompressionService

===== Resource compress(Resource input, int qualityLevel);
Compresses given resource.

*Parameters*

- input - resource that should be compressed
- qualityLevel - a percent indicating the desired quality level

*Returns*

Compressed resource. If IOException was thrown during compression returns uncompressed resource.

_[Req-SIP-67]_

==== Glossary
[%autowidth]
|===
|Term | Definition

|ETag
|Is a string which specifies the version of a resource on the Google Api side. It usually refers to tile (satellite image of Earth area) which can change (by updated by Google) over time. Sip service is using etag to verify if has up-to-date version of certain tail and not download the same resource multiple times. Therefor etag is sent between Sip and Google goth ways. If requested tile is up-to-date, then google sent back '302 - Not Modified' response instead of actual resource. +
Remark: in the code you can see etag under _ifNoneMatch_ parameter.

| Zoom{nbsp}Level
| Google divides world map to matrix of tiles. Zoom level specifies amount of rows/columns that matrix will have. The highest zoom level is, the more tiles world division will have. Higher zoom level also means smaller and more accurate tiles. +
For more information on a tiles and zoom levels go to link:https://developers.google.com/maps/documentation/javascript/coordinates#tile-coordinates[Google documentation]

| Tile
| Satellite image of area of Earth. Sip uses _jpeg_ format for the images.

| Tile Coordinates
| Set of 3 integers (x, y and zoom) that specifies tile location on the map of the world. Google divides world map to matrix of tiles. Zoom level specifies amount of rows/columns that matrix will have. Tile coordinates x, y specifies row and column of the metrics. +
For more information on a tiles and zoom levels go to link:https://developers.google.com/maps/documentation/javascript/coordinates#tile-coordinates[Google documentation]

| View Port
| It is a 4 degree coordinate specifying certain area of the world. Position are south (latitude), north (latitude), west (longitude), east (longitude).

| Max Zoom
| Maximum zoom level that has satellite tile image available for given area; this value is returned to client in header of HTTP 404 response (see link:https://confluence.tomtomgroup.com/x/ccVKN[Max Zoom header in 404 response])

| No-Tile Area
| area that does not contain tiles for given zoom level; areas are calculated preemptively to efficiently respond with most accurate max-zoom value (see No-tile Areas section in link:https://confluence.tomtomgroup.com/x/ccVKN[Max Zoom header in 404 response])

| Quality Level
| value defining what should be JPEG quality of returned tiles; if map provider gives greater quality, SIP is re-compressing image to defined value (see link:https://confluence.tomtomgroup.com/x/EL5KN[Image Compression - JPEG])

|===
