# This is a basic workflow to help you get started with Actions

name: Publish docs as github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    steps:
      - uses: actions/checkout@v2
      - name: build-doc
        run: asciidoctor -o docs/index.html docs/SatelliteImageProxyServiceDetailedDesign.adoc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./
